version: "3.1"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/data/storage"
      - "./config:/data/conf"
      - "./plugins:/data/plugins"
networks:
  node-network:
    driver: bridge
